name: tianqi

language: ruby
cache: bundler
rvm:
  - 2.7.0
before_install: gem install bundler -v 2.1.4

on:
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
 build:
    runs-on: ubuntu-latest
    name: send msg
    steps:
      - name: run rb
        run: ruby ./tianqi.rb
