name: Hello World	

on: [push]	

jobs:	
  hello_world_job:		
    runs-on: ubuntu-latest	
    steps:	
    - uses: timburgan/actions-example/.github/actions/hello_world@master	
      with:	
        repo-token: ${{ secrets.GITHUB_TOKEN }}	
        hello_message: 'Ohhh nice...!'
