name: ruby-versions
on:
    push:
      branches:
        - main
jobs:
  run:
    name: Ruby 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        version: [2.6.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: use-ruby ${{ matrix.version }}
      uses: ./
      with:
        ruby-version: ${{ matrix.version}}

    - name: ruby version
      run: ruby -v
